version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8080

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/gb.conf:ro,cached
      - ./public:/usr/share/nginx/html/public:ro,cached
    command: [nginx-debug, '-g', 'daemon off;']
